version: "3.7"

services:
  django:
    build:
      target: development
    command: sleep infinity
    volumes:
      - .:/workspace

  db:
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_backup:/backups

volumes:
  db_data:
  db_backup:
