version: "3.7"

services:
  django:
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://helios:localpassword@db:5432/helios
      DJANGO_SECRET_KEY: notsecretatall
      DJANGO_SETTINGS_MODULE: settings
      EMAIL_BACKEND: console
      POSTGRES_PASSWORD: localpassword

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: helios
      POSTGRES_PASSWORD: localpassword
